name: Webhook

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Parse Content
      uses: actions/github-script@v6
      with:
          script: |
            const repo = context.repo.repo
            const owner = context.repo.owner
            const shortRepo = repo.replace(owner, '')
            core.exportVariable('shortRepo', shortRepo)
    - name: Webhook call
      uses: fjogeleit/http-request-action@v1
      continue-on-error: true
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        data: '{"token": "${{ secrets.WEBHOOK_TOKEN }}", "repoName": "${{ env.shortRepo }}"}'
